// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pkg/proto/greeter.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GreeterService service

type GreeterService interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...client.CallOption) (*GreetResponse, error)
}

type greeterService struct {
	c    client.Client
	name string
}

func NewGreeterService(name string, c client.Client) GreeterService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "greeterservice"
	}
	return &greeterService{
		c:    c,
		name: name,
	}
}

func (c *greeterService) Greet(ctx context.Context, in *GreetRequest, opts ...client.CallOption) (*GreetResponse, error) {
	req := c.c.NewRequest(c.name, "GreeterService.Greet", in)
	out := new(GreetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GreeterService service

type GreeterServiceHandler interface {
	Greet(context.Context, *GreetRequest, *GreetResponse) error
}

func RegisterGreeterServiceHandler(s server.Server, hdlr GreeterServiceHandler, opts ...server.HandlerOption) error {
	type greeterService interface {
		Greet(ctx context.Context, in *GreetRequest, out *GreetResponse) error
	}
	type GreeterService struct {
		greeterService
	}
	h := &greeterServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&GreeterService{h}, opts...))
}

type greeterServiceHandler struct {
	GreeterServiceHandler
}

func (h *greeterServiceHandler) Greet(ctx context.Context, in *GreetRequest, out *GreetResponse) error {
	return h.GreeterServiceHandler.Greet(ctx, in, out)
}
